version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    # volumes:
    #   - ./frontend:/frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - 3008:3000
    platform: linux/amd64
    env_file:
      - ./frontend/.env.development

  backend:
    # volumes:
    #   - ./backend:/backend
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    ports:
      - 3009:3000
    platform: linux/amd64
    env_file:
      - ./backend/.env.local

volumes:
  mysql_data:
